CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	PHONE_NUMBER VARCHAR(15),
	HIRE_DATE DATE NOT NULL,
	JOB_ID INTEGER NOT NULL,
	SALARY NUMERIC(10, 2),
	MANAGER_ID INTEGER,
	DEPARTMENT_ID INTEGER
);

INSERT INTO
	EMPLOYEE (
		EMPLOYEE_ID,
		FIRST_NAME,
		LAST_NAME,
		EMAIL,
		PHONE_NUMBER,
		HIRE_DATE,
		JOB_ID,
		SALARY,
		MANAGER_ID,
		DEPARTMENT_ID
	)
VALUES
	(
		1,
		'Shreya',
		'Gor',
		'shreyagor2004@gmail.com',
		'8799523840',
		'2023-01-15',
		1,
		60000.00,
		NULL,
		10
	),
	(
		2,
		'Ayushi',
		'Patel',
		'ayushi123@gmail.com',
		'9825067834',
		'2023-02-20',
		2,
		65000.00,
		1,
		20
	),
	(
		3,
		'Vidhi',
		'Joshi',
		'vidhi234@gmail.com',
		'9871234067',
		'2022-01-17',
		3,
		80000.00,
		NULL,
		30
	);

SELECT
	*
FROM
	EMPLOYEE;

UPDATE EMPLOYEE
SET
	SALARY = 70000.00
WHERE
	EMPLOYEE_ID = 1;

DELETE FROM EMPLOYEE WHERE EMPLOYEE_ID =3;

CREATE TABLE ORDERS (
    EMPLOYEE_ID INTEGER NOT NULL REFERENCES EMPLOYEE(EMPLOYEE_ID),
    ORDER_DATE timestamp with time zone NOT NULL DEFAULT now(),
    ORDER_NUMBER CHARACTER VARYING(50) NOT NULL,
    ORDER_AMOUNT DECIMAL(10,2) NOT NULL );

INSERT INTO ORDERS (EMPLOYEE_ID, ORDER_DATE, ORDER_NUMBER, ORDER_AMOUNT) VALUES
  (1, '2024-01-01', 'ORD001', 50.00),
  (2, '2024-01-01', 'ORD002', 35.75),
  (3, '2024-01-01', 'ORD003', 100.00);

SELECT * FROM EMPLOYEE as e
LEFT JOIN ORDERS as o
ON e.EMPLOYEE_ID = o.EMPLOYEE_ID

SELECT * FROM ORDERS
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE )

SELECT
    EMPLOYEE_ID,
	FIRST_NAME,
	EMAIL
FROM
	EMPLOYEE
WHERE
	EXISTS (
		SELECT
			1
		FROM
			ORDERS
		WHERE
			ORDERS.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
	);
